<!DOCTYPE html>
<html lang="en">

<head>


  <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, viewport-fit=cover"
    />
    <base href="/">
    <title>Project Madurai School</title>

    
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/images/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="/images/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="/images/favicon-16x16.png"
    />
    <link rel="manifest" href="/images/site.webmanifest" />

    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />


    

    <link rel="stylesheet" href="/css/style.css"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
      integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ="
      crossorigin="anonymous"
    />



  


</head>

<body>
  <main class="container mt-5 w-100 h-100">
    <nav class="navbar navbar-expand-md navbar-light bg-white py-0 fixed-top">
  <div class="container-fluid border-bottom border-top-1 shadow-sm bg-body">
    <a class="navbar-brand lh-1" href="/">
      
      
        <span class="text-primary"><strong>Project Madurai</strong></span><br>
        <p class="text-muted text-end w-100 p-0 mb-0"><small class="dropdown-toggle">தமிழ்</small></p>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="/books/javascript">Javascript</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/books/c">C</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/practices/java">Java</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/posts">Blog</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>
      <ul class="navbar-nav secured">
        <li class="nav-item btn pe-0">
          <a class="nav-link" href="/chat"><i class="far fa-comment-dots fa-2x"></i></a>
        </li>
        <li class="nav-item pe-0 dropdown">
          
          <div class="btn-group bg-light">
            <a class="btn btn-toggle pe-0" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="d-flex bd-highlight">
                <div class="w-100 bd-highlight text-end">
                  <h6 class="text-muted fw-bold">தமிழ்ச் சங்கம்</h6>
                  <small class="text-muted">திருவள்ளுவர் கழகம்</small>
               </div>
                <div class="flex-shrink-1 bd-highlight">
                  <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-circle img-thumbnail avatar"
                style="vertical-align: middle;border-radius: 50%; width: 3rem; margin-right: 10px;" alt="avatar">
                </div>
                
                
              </div>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdown03">
              <li><a class="dropdown-item" href="javascript://">Profile</a></li>
              <li><a class="dropdown-item" href="/campuses/tamil-sangam">Campus</a></li>
              <li><a class="dropdown-item logout" href="javascript://">Logout</a></li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="row py-5 w-100 h-100">
       

  <nav class="navbar border-1 border-bottom">
  <div class="row w-100">
    <div class="col-4">
      <a href="/books/javascript/promises-async-await/promises-chaining">Promises chaining</a>
    </div>
    <div class="col-4 mb-2 text-center">
      <a class="text-dark"
        href="/books/javascript/promises-async-await">Promises, async/await</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a href="/books/javascript/promises-async-await/promise-api">Promise API</a>
    </div>
  </div>
</nav>

<main id="content" class="pt-3"><h1 id="error-handling-with-promises">Error handling with promises</h1>
<p>Promise chains are great at error handling. When a promise rejects, the control jumps to the closest rejection handler. That&rsquo;s very convenient in practice.</p>
<p>For instance, in the code below the URL to <code>fetch</code> is wrong (no such site) and <code>.catch</code> handles the error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#f92672">*!*</span>
<span style="color:#a6e22e">fetch</span>(<span style="color:#e6db74">&#39;https://no-such-server.blabla&#39;</span>) <span style="color:#75715e">// rejects
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
  .<span style="color:#a6e22e">then</span>(<span style="color:#a6e22e">response</span> =&gt; <span style="color:#a6e22e">response</span>.<span style="color:#a6e22e">json</span>())
  .<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">err</span> =&gt; <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>)) <span style="color:#75715e">// TypeError: failed to fetch (the text may vary)
</span></code></pre></div><p>As you can see, the <code>.catch</code> doesn&rsquo;t have to be immediate. It may appear after one or maybe several <code>.then</code>.</p>
<p>Or, maybe, everything is all right with the site, but the response is not valid JSON. The easiest way to catch all errors is to append <code>.catch</code> to the end of chain:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#a6e22e">fetch</span>(<span style="color:#e6db74">&#39;/article/promise-chaining/user.json&#39;</span>)
  .<span style="color:#a6e22e">then</span>(<span style="color:#a6e22e">response</span> =&gt; <span style="color:#a6e22e">response</span>.<span style="color:#a6e22e">json</span>())
  .<span style="color:#a6e22e">then</span>(<span style="color:#a6e22e">user</span> =&gt; <span style="color:#a6e22e">fetch</span>(<span style="color:#e6db74">`https://api.github.com/users/</span><span style="color:#e6db74">${</span><span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span><span style="color:#e6db74">}</span><span style="color:#e6db74">`</span>))
  .<span style="color:#a6e22e">then</span>(<span style="color:#a6e22e">response</span> =&gt; <span style="color:#a6e22e">response</span>.<span style="color:#a6e22e">json</span>())
  .<span style="color:#a6e22e">then</span>(<span style="color:#a6e22e">githubUser</span> =&gt; <span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {
    <span style="color:#66d9ef">let</span> <span style="color:#a6e22e">img</span> <span style="color:#f92672">=</span> document.<span style="color:#a6e22e">createElement</span>(<span style="color:#e6db74">&#39;img&#39;</span>);
    <span style="color:#a6e22e">img</span>.<span style="color:#a6e22e">src</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">githubUser</span>.<span style="color:#a6e22e">avatar_url</span>;
    <span style="color:#a6e22e">img</span>.<span style="color:#a6e22e">className</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;promise-avatar-example&#34;</span>;
    document.<span style="color:#a6e22e">body</span>.<span style="color:#a6e22e">append</span>(<span style="color:#a6e22e">img</span>);

    <span style="color:#a6e22e">setTimeout</span>(() =&gt; {
      <span style="color:#a6e22e">img</span>.<span style="color:#a6e22e">remove</span>();
      <span style="color:#a6e22e">resolve</span>(<span style="color:#a6e22e">githubUser</span>);
    }, <span style="color:#ae81ff">3000</span>);
  }))
<span style="color:#f92672">*!*</span>
  .<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">error</span> =&gt; <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">error</span>.<span style="color:#a6e22e">message</span>));
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
</code></pre></div><p>Normally, such <code>.catch</code> doesn&rsquo;t trigger at all. But if any of the promises above rejects (a network problem or invalid json or whatever), then it would catch it.</p>
<h2 id="implicit-trycatch">Implicit try..catch</h2>
<p>The code of a promise executor and promise handlers has an &ldquo;invisible <code>try..catch</code>&rdquo; around it. If an exception happens, it gets caught and treated as a rejection.</p>
<p>For instance, this code:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {
<span style="color:#f92672">*!*</span>
  <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Whoops!&#34;</span>);
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
}).<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">alert</span>); <span style="color:#75715e">// Error: Whoops!
</span></code></pre></div><p>&hellip;Works exactly the same as this:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {
<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">reject</span>(<span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Whoops!&#34;</span>));
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
}).<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">alert</span>); <span style="color:#75715e">// Error: Whoops!
</span></code></pre></div><p>The &ldquo;invisible <code>try..catch</code>&rdquo; around the executor automatically catches the error and turns it into rejected promise.</p>
<p>This happens not only in the executor function, but in its handlers as well. If we <code>throw</code> inside a <code>.then</code> handler, that means a rejected promise, so the control jumps to the nearest error handler.</p>
<p>Here&rsquo;s an example:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {
  <span style="color:#a6e22e">resolve</span>(<span style="color:#e6db74">&#34;ok&#34;</span>);
}).<span style="color:#a6e22e">then</span>((<span style="color:#a6e22e">result</span>) =&gt; {
<span style="color:#f92672">*!*</span>
  <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Whoops!&#34;</span>); <span style="color:#75715e">// rejects the promise
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
}).<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">alert</span>); <span style="color:#75715e">// Error: Whoops!
</span></code></pre></div><p>This happens for all errors, not just those caused by the <code>throw</code> statement. For example, a programming error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {
  <span style="color:#a6e22e">resolve</span>(<span style="color:#e6db74">&#34;ok&#34;</span>);
}).<span style="color:#a6e22e">then</span>((<span style="color:#a6e22e">result</span>) =&gt; {
<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">blabla</span>(); <span style="color:#75715e">// no such function
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
}).<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">alert</span>); <span style="color:#75715e">// ReferenceError: blabla is not defined
</span></code></pre></div><p>The final <code>.catch</code> not only catches explicit rejections, but also accidental errors in the handlers above.</p>
<h2 id="rethrowing">Rethrowing</h2>
<p>As we already noticed, <code>.catch</code> at the end of the chain is similar to <code>try..catch</code>. We may have as many <code>.then</code> handlers as we want, and then use a single <code>.catch</code> at the end to handle errors in all of them.</p>
<p>In a regular <code>try..catch</code> we can analyze the error and maybe rethrow it if it can&rsquo;t be handled. The same thing is possible for promises.</p>
<p>If we <code>throw</code> inside <code>.catch</code>, then the control goes to the next closest error handler. And if we handle the error and finish normally, then it continues to the next closest successful <code>.then</code> handler.</p>
<p>In the example below the <code>.catch</code> successfully handles the error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#75715e">// the execution: catch -&gt; then
</span><span style="color:#75715e"></span><span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {

  <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Whoops!&#34;</span>);

}).<span style="color:#66d9ef">catch</span>(<span style="color:#66d9ef">function</span>(<span style="color:#a6e22e">error</span>) {

  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#34;The error is handled, continue normally&#34;</span>);

}).<span style="color:#a6e22e">then</span>(() =&gt; <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#34;Next successful handler runs&#34;</span>));
</code></pre></div><p>Here the <code>.catch</code> block finishes normally. So the next successful <code>.then</code> handler is called.</p>
<p>In the example below we see the other situation with <code>.catch</code>. The handler <code>(*)</code> catches the error and just can&rsquo;t handle it (e.g. it only knows how to handle <code>URIError</code>), so it throws it again:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#75715e">// the execution: catch -&gt; catch
</span><span style="color:#75715e"></span><span style="color:#66d9ef">new</span> Promise((<span style="color:#a6e22e">resolve</span>, <span style="color:#a6e22e">reject</span>) =&gt; {

  <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Whoops!&#34;</span>);

}).<span style="color:#66d9ef">catch</span>(<span style="color:#66d9ef">function</span>(<span style="color:#a6e22e">error</span>) { <span style="color:#75715e">// (*)
</span><span style="color:#75715e"></span>
  <span style="color:#66d9ef">if</span> (<span style="color:#a6e22e">error</span> <span style="color:#66d9ef">instanceof</span> <span style="color:#a6e22e">URIError</span>) {
    <span style="color:#75715e">// handle it
</span><span style="color:#75715e"></span>  } <span style="color:#66d9ef">else</span> {
    <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#34;Can&#39;t handle such error&#34;</span>);

<span style="color:#f92672">*!*</span>
    <span style="color:#66d9ef">throw</span> <span style="color:#a6e22e">error</span>; <span style="color:#75715e">// throwing this or another error jumps to the next catch
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
  }

}).<span style="color:#a6e22e">then</span>(<span style="color:#66d9ef">function</span>() {
  <span style="color:#75715e">/* doesn&#39;t run here */</span>
}).<span style="color:#66d9ef">catch</span>(<span style="color:#a6e22e">error</span> =&gt; { <span style="color:#75715e">// (**)
</span><span style="color:#75715e"></span>
  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">`The unknown error has occurred: </span><span style="color:#e6db74">${</span><span style="color:#a6e22e">error</span><span style="color:#e6db74">}</span><span style="color:#e6db74">`</span>);
  <span style="color:#75715e">// don&#39;t return anything =&gt; execution goes the normal way
</span><span style="color:#75715e"></span>
});
</code></pre></div><p>The execution jumps from the first <code>.catch</code> <code>(*)</code> to the next one <code>(**)</code> down the chain.</p>
<h2 id="unhandled-rejections">Unhandled rejections</h2>
<p>What happens when an error is not handled? For instance, we forgot to append <code>.catch</code> to the end of the chain, like here:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">new</span> Promise(<span style="color:#66d9ef">function</span>() {
  <span style="color:#a6e22e">noSuchFunction</span>(); <span style="color:#75715e">// Error here (no such function)
</span><span style="color:#75715e"></span>})
  .<span style="color:#a6e22e">then</span>(() =&gt; {
    <span style="color:#75715e">// successful promise handlers, one or more
</span><span style="color:#75715e"></span>  }); <span style="color:#75715e">// without .catch at the end!
</span></code></pre></div><p>In case of an error, the promise becomes rejected, and the execution should jump to the closest rejection handler. But there is none. So the error gets &ldquo;stuck&rdquo;. There&rsquo;s no code to handle it.</p>
<p>In practice, just like with regular unhandled errors in code, it means that something has gone terribly wrong.</p>
<p>What happens when a regular error occurs and is not caught by <code>try..catch</code>? The script dies with a message in the console. A similar thing happens with unhandled promise rejections.</p>
<p>The JavaScript engine tracks such rejections and generates a global error in that case. You can see it in the console if you run the example above.</p>
<p>In the browser we can catch such errors using the event <code>unhandledrejection</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#f92672">*!*</span>
window.<span style="color:#a6e22e">addEventListener</span>(<span style="color:#e6db74">&#39;unhandledrejection&#39;</span>, <span style="color:#66d9ef">function</span>(<span style="color:#a6e22e">event</span>) {
  <span style="color:#75715e">// the event object has two special properties:
</span><span style="color:#75715e"></span>  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">event</span>.<span style="color:#a6e22e">promise</span>); <span style="color:#75715e">// [object Promise] - the promise that generated the error
</span><span style="color:#75715e"></span>  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">event</span>.<span style="color:#a6e22e">reason</span>); <span style="color:#75715e">// Error: Whoops! - the unhandled error object
</span><span style="color:#75715e"></span>});
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

<span style="color:#66d9ef">new</span> Promise(<span style="color:#66d9ef">function</span>() {
  <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Whoops!&#34;</span>);
}); <span style="color:#75715e">// no catch to handle the error
</span></code></pre></div><p>The event is the part of the <a href="https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections">HTML standard</a>.</p>
<p>If an error occurs, and there&rsquo;s no <code>.catch</code>, the <code>unhandledrejection</code> handler triggers, and gets the <code>event</code> object with the information about the error, so we can do something.</p>
<p>Usually such errors are unrecoverable, so our best way out is to inform the user about the problem and probably report the incident to the server.</p>
<p>In non-browser environments like Node.js there are other ways to track unhandled errors.</p>
<h2 id="summary">Summary</h2>
<ul>
<li><code>.catch</code> handles errors in promises of all kinds: be it a <code>reject()</code> call, or an error thrown in a handler.</li>
<li>We should place <code>.catch</code> exactly in places where we want to handle errors and know how to handle them. The handler should analyze errors (custom error classes help) and rethrow unknown ones (maybe they are programming mistakes).</li>
<li>It&rsquo;s ok not to use <code>.catch</code> at all, if there&rsquo;s no way to recover from an error.</li>
<li>In any case we should have the <code>unhandledrejection</code> event handler (for browsers, and analogs for other environments) to track unhandled errors and inform the user (and probably our server) about them, so that our app never &ldquo;just dies&rdquo;.</li>
</ul>
</main>


<div class="modal fade" id="noteModel" tabindex="-1" aria-labelledby="noteModelLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="noteModelLabel">Note</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <textarea class="form-control" id="noteText" rows="3"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


    </div>
    
  </main>
  
  



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confimation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
          <button type="button" class="btn btn-primary">Yes</button>
        </div>
      </div>
    </div>
  </div>

<div aria-live="polite" aria-atomic="true">
  <div class="toast-container position-absolute top-0 start-0 p-5 mt-5" id="toast-container">
    
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
<script type="text/javascript" src="/js/app.js"></script>



  
  
  

<script type="text/javascript" src="/js/chapter.js"></script>


  
</body>

</html>