<!DOCTYPE html>
<html lang="en">

<head>


  <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, viewport-fit=cover"
    />
    <base href="/">
    <title>Project Madurai School</title>

    
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/images/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="/images/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="/images/favicon-16x16.png"
    />
    <link rel="manifest" href="/images/site.webmanifest" />

    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />


    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
      integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ="
      crossorigin="anonymous"
    />



  


</head>

<body>
  <main class="container mt-5 w-100 h-100">
    <nav class="navbar navbar-expand-md navbar-light bg-white py-0 fixed-top">
  <div class="container-fluid border-bottom border-top-1 shadow-sm bg-body">
    <a class="navbar-brand lh-1" href="/">
      
      
        <span class="text-primary"><strong>Project Madurai</strong></span><br>
        <p class="text-muted text-end w-100 p-0 mb-0"><small class="dropdown-toggle">தமிழ்</small></p>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="/books/javascript">Javascript</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/books/c">C</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/practices/java">Java</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/posts">Blog</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>
      <ul class="navbar-nav secured">
        <li class="nav-item btn pe-0">
          <a class="nav-link" href="/chat"><i class="far fa-comment-dots fa-2x"></i></a>
        </li>
        <li class="nav-item pe-0 dropdown">
          
          <div class="btn-group bg-light">
            <a class="btn btn-toggle pe-0" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="d-flex bd-highlight">
                <div class="w-100 bd-highlight text-end">
                  <h6 class="text-muted fw-bold">தமிழ்ச் சங்கம்</h6>
                  <small class="text-muted">திருவள்ளுவர் கழகம்</small>
               </div>
                <div class="flex-shrink-1 bd-highlight">
                  <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="img-circle img-thumbnail avatar"
                style="vertical-align: middle;border-radius: 50%; width: 3rem; margin-right: 10px;" alt="avatar">
                </div>
                
                
              </div>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdown03">
              <li><a class="dropdown-item" href="javascript://">Profile</a></li>
              <li><a class="dropdown-item" href="/campuses/tamil-sangam">Campus</a></li>
              <li><a class="dropdown-item logout" href="javascript://">Logout</a></li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="row py-5 w-100 h-100">
       

  <nav class="navbar border-1 border-bottom">
  <div class="row w-100">
    <div class="col-4">
      
    </div>
    <div class="col-4 mb-2 text-center">
      <a class="text-dark"
        href="/books/javascript/error-handling">Error Handling</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a href="/books/javascript/error-handling/custom-errors">Custom errors, extending Error</a>
    </div>
  </div>
</nav>

<main id="content" class="pt-3"><h1 id="error-handling-trycatch">Error handling, &ldquo;try&hellip;catch&rdquo;</h1>
<p>No matter how great we are at programming, sometimes our scripts have errors. They may occur because of our mistakes, an unexpected user input, an erroneous server response, and for a thousand other reasons.</p>
<p>Usually, a script &ldquo;dies&rdquo; (immediately stops) in case of an error, printing it to console.</p>
<p>But there&rsquo;s a syntax construct <code>try...catch</code> that allows us to &ldquo;catch&rdquo; errors so the script can, instead of dying, do something more reasonable.</p>
<h2 id="the-trycatch-syntax">The &ldquo;try&hellip;catch&rdquo; syntax</h2>
<p>The <code>try...catch</code> construct has two main blocks: <code>try</code>, and then <code>catch</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {

  <span style="color:#75715e">// code...
</span><span style="color:#75715e"></span>
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {

  <span style="color:#75715e">// error handling
</span><span style="color:#75715e"></span>
}
</code></pre></div><p>It works like this:</p>
<ol>
<li>First, the code in <code>try {...}</code> is executed.</li>
<li>If there were no errors, then <code>catch (err)</code> is ignored: the execution reaches the end of <code>try</code> and goes on, skipping <code>catch</code>.</li>
<li>If an error occurs, then the <code>try</code> execution is stopped, and control flows to the beginning of <code>catch (err)</code>. The <code>err</code> variable (we can use any name for it) will contain an error object with details about what happened.</li>
</ol>
<p><img src="try-catch-flow.svg" alt=""></p>
<p>So, an error inside the <code>try {...}</code> block does not kill the script &ndash; we have a chance to handle it in <code>catch</code>.</p>
<p>Let&rsquo;s look at some examples.</p>
<ul>
<li>
<p>An errorless example: shows <code>alert</code> <code>(1)</code> and <code>(2)</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {

  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#39;Start of try runs&#39;</span>);  <span style="color:#75715e">// *!*(1) &lt;--*/!*
</span><span style="color:#75715e"></span>
  <span style="color:#75715e">// ...no errors here
</span><span style="color:#75715e"></span>
  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#39;End of try runs&#39;</span>);   <span style="color:#75715e">// *!*(2) &lt;--*/!*
</span><span style="color:#75715e"></span>
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {

  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#39;Catch is ignored, because there are no errors&#39;</span>); <span style="color:#75715e">// (3)
</span><span style="color:#75715e"></span>
}
</code></pre></div></li>
<li>
<p>An example with an error: shows <code>(1)</code> and <code>(3)</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {

  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#39;Start of try runs&#39;</span>);  <span style="color:#75715e">// *!*(1) &lt;--*/!*
</span><span style="color:#75715e"></span>
<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">lalala</span>; <span style="color:#75715e">// error, variable is not defined!
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#39;End of try (never reached)&#39;</span>);  <span style="color:#75715e">// (2)
</span><span style="color:#75715e"></span>
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {

  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">`Error has occurred!`</span>); <span style="color:#75715e">// *!*(3) &lt;--*/!*
</span><span style="color:#75715e"></span>
}
</code></pre></div></li>
</ul>
<p>````warn header=&quot;<code>try...catch</code> only works for runtime errors&quot;
For <code>try...catch</code> to work, the code must be runnable. In other words, it should be valid JavaScript.</p>
<p>It won&rsquo;t work if the code is syntactically wrong, for instance it has unmatched curly braces:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  {{{{{{{{{{{{
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#34;The engine can&#39;t understand this code, it&#39;s invalid&#34;</span>);
}
</code></pre></div><p>The JavaScript engine first reads the code, and then runs it. The errors that occur on the reading phase are called &ldquo;parse-time&rdquo; errors and are unrecoverable (from inside that code). That&rsquo;s because the engine can&rsquo;t understand the code.</p>
<p>So, <code>try...catch</code> can only handle errors that occur in valid code. Such errors are called &ldquo;runtime errors&rdquo; or, sometimes, &ldquo;exceptions&rdquo;.</p>
<pre><code>

````warn header=&quot;`try...catch` works synchronously&quot;
If an exception happens in &quot;scheduled&quot; code, like in `setTimeout`, then `try...catch` won't catch it:

```js run
try {
  setTimeout(function() {
    noSuchVariable; // script will die here
  }, 1000);
} catch (err) {
  alert( &quot;won't work&quot; );
}
```

That's because the function itself is executed later, when the engine has already left the `try...catch` construct.

To catch an exception inside a scheduled function, `try...catch` must be inside that function:
```js run
setTimeout(function() {
  try {    
    noSuchVariable; // try...catch handles the error!
  } catch {
    alert( &quot;error is caught here!&quot; );
  }
}, 1000);
```
</code></pre><h2 id="error-object">Error object</h2>
<p>When an error occurs, JavaScript generates an object containing the details about it. The object is then passed as an argument to <code>catch</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) { <span style="color:#75715e">// &lt;-- the &#34;error object&#34;, could use another word instead of err
</span><span style="color:#75715e"></span>  <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>}
</code></pre></div><p>For all built-in errors, the error object has two main properties:</p>
<dl>
<dt><code>name</code></dt>
<dd>Error name. For instance, for an undefined variable that&rsquo;s <code>&quot;ReferenceError&quot;</code>.</dd>
<dt><code>message</code></dt>
<dd>Textual message about error details.</dd>
</dl>
<p>There are other non-standard properties available in most environments. One of most widely used and supported is:</p>
<dl>
<dt><code>stack</code></dt>
<dd>Current call stack: a string with information about the sequence of nested calls that led to the error. Used for debugging purposes.</dd>
</dl>
<p>For instance:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">lalala</span>; <span style="color:#75715e">// error, variable is not defined!
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">name</span>); <span style="color:#75715e">// ReferenceError
</span><span style="color:#75715e"></span>  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">message</span>); <span style="color:#75715e">// lalala is not defined
</span><span style="color:#75715e"></span>  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">stack</span>); <span style="color:#75715e">// ReferenceError: lalala is not defined at (...call stack)
</span><span style="color:#75715e"></span>
  <span style="color:#75715e">// Can also show an error as a whole
</span><span style="color:#75715e"></span>  <span style="color:#75715e">// The error is converted to string as &#34;name: message&#34;
</span><span style="color:#75715e"></span>  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>); <span style="color:#75715e">// ReferenceError: lalala is not defined
</span><span style="color:#75715e"></span>}
</code></pre></div><h2 id="optional-catch-binding">Optional &ldquo;catch&rdquo; binding</h2>
<p>[recent browser=new]</p>
<p>If we don&rsquo;t need error details, <code>catch</code> may omit it:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>} <span style="color:#66d9ef">catch</span> { <span style="color:#75715e">// &lt;-- without (err)
</span><span style="color:#75715e"></span>  <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>}
</code></pre></div><h2 id="using-trycatch">Using &ldquo;try&hellip;catch&rdquo;</h2>
<p>Let&rsquo;s explore a real-life use case of <code>try...catch</code>.</p>
<p>As we already know, JavaScript supports the <a href="mdn:js/JSON/parse">JSON.parse(str)</a> method to read JSON-encoded values.</p>
<p>Usually it&rsquo;s used to decode data received over the network, from the server or another source.</p>
<p>We receive it and call <code>JSON.parse</code> like this:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;{&#34;name&#34;:&#34;John&#34;, &#34;age&#34;: 30}&#39;</span>; <span style="color:#75715e">// data from the server
</span><span style="color:#75715e"></span>
<span style="color:#f92672">*!*</span>
<span style="color:#66d9ef">let</span> <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#a6e22e">json</span>); <span style="color:#75715e">// convert the text representation to JS object
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

<span style="color:#75715e">// now user is an object with properties from the string
</span><span style="color:#75715e"></span><span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span> ); <span style="color:#75715e">// John
</span><span style="color:#75715e"></span><span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">age</span> );  <span style="color:#75715e">// 30
</span></code></pre></div><p>You can find more detailed information about JSON in the <a href="info:json">info:json</a> chapter.</p>
<p><strong>If <code>json</code> is malformed, <code>JSON.parse</code> generates an error, so the script &ldquo;dies&rdquo;.</strong></p>
<p>Should we be satisfied with that? Of course not!</p>
<p>This way, if something&rsquo;s wrong with the data, the visitor will never know that (unless they open the developer console). And people really don&rsquo;t like when something &ldquo;just dies&rdquo; without any error message.</p>
<p>Let&rsquo;s use <code>try...catch</code> to handle the error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;{ bad json }&#34;</span>;

<span style="color:#66d9ef">try</span> {

<span style="color:#f92672">*!*</span>
  <span style="color:#66d9ef">let</span> <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#a6e22e">json</span>); <span style="color:#75715e">// &lt;-- when an error occurs...
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
  <span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span> ); <span style="color:#75715e">// doesn&#39;t work
</span><span style="color:#75715e"></span>
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
<span style="color:#f92672">*!*</span>
  <span style="color:#75715e">// ...the execution jumps here
</span><span style="color:#75715e"></span>  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#34;Our apologies, the data has errors, we&#39;ll try to request it one more time.&#34;</span> );
  <span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">name</span> );
  <span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">message</span> );
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
}
</code></pre></div><p>Here we use the <code>catch</code> block only to show the message, but we can do much more: send a new network request, suggest an alternative to the visitor, send information about the error to a logging facility, &hellip; . All much better than just dying.</p>
<h2 id="throwing-our-own-errors">Throwing our own errors</h2>
<p>What if <code>json</code> is syntactically correct, but doesn&rsquo;t have a required <code>name</code> property?</p>
<p>Like this:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;{ &#34;age&#34;: 30 }&#39;</span>; <span style="color:#75715e">// incomplete data
</span><span style="color:#75715e"></span>
<span style="color:#66d9ef">try</span> {

  <span style="color:#66d9ef">let</span> <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#a6e22e">json</span>); <span style="color:#75715e">// &lt;-- no errors
</span><span style="color:#75715e"></span><span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span> ); <span style="color:#75715e">// no name!
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#34;doesn&#39;t execute&#34;</span> );
}
</code></pre></div><p>Here <code>JSON.parse</code> runs normally, but the absence of <code>name</code> is actually an error for us.</p>
<p>To unify error handling, we&rsquo;ll use the <code>throw</code> operator.</p>
<h3 id="throw-operator">&ldquo;Throw&rdquo; operator</h3>
<p>The <code>throw</code> operator generates an error.</p>
<p>The syntax is:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">throw</span> <span style="color:#f92672">&lt;</span><span style="color:#a6e22e">error</span> <span style="color:#a6e22e">object</span><span style="color:#f92672">&gt;</span>
</code></pre></div><p>Technically, we can use anything as an error object. That may be even a primitive, like a number or a string, but it&rsquo;s better to use objects, preferably with <code>name</code> and <code>message</code> properties (to stay somewhat compatible with built-in errors).</p>
<p>JavaScript has many built-in constructors for standard errors: <code>Error</code>, <code>SyntaxError</code>, <code>ReferenceError</code>, <code>TypeError</code> and others. We can use them to create error objects as well.</p>
<p>Their syntax is:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">error</span> <span style="color:#f92672">=</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#a6e22e">message</span>);
<span style="color:#75715e">// or
</span><span style="color:#75715e"></span><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">error</span> <span style="color:#f92672">=</span> <span style="color:#66d9ef">new</span> <span style="color:#a6e22e">SyntaxError</span>(<span style="color:#a6e22e">message</span>);
<span style="color:#66d9ef">let</span> <span style="color:#a6e22e">error</span> <span style="color:#f92672">=</span> <span style="color:#66d9ef">new</span> <span style="color:#a6e22e">ReferenceError</span>(<span style="color:#a6e22e">message</span>);
<span style="color:#75715e">// ...
</span></code></pre></div><p>For built-in errors (not for any objects, just for errors), the <code>name</code> property is exactly the name of the constructor. And <code>message</code> is taken from the argument.</p>
<p>For instance:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">error</span> <span style="color:#f92672">=</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Things happen o_O&#34;</span>);

<span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">error</span>.<span style="color:#a6e22e">name</span>); <span style="color:#75715e">// Error
</span><span style="color:#75715e"></span><span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">error</span>.<span style="color:#a6e22e">message</span>); <span style="color:#75715e">// Things happen o_O
</span></code></pre></div><p>Let&rsquo;s see what kind of error <code>JSON.parse</code> generates:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#e6db74">&#34;{ bad json o_O }&#34;</span>);
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">name</span>); <span style="color:#75715e">// SyntaxError
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
  <span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">message</span>); <span style="color:#75715e">// Unexpected token b in JSON at position 2
</span><span style="color:#75715e"></span>}
</code></pre></div><p>As we can see, that&rsquo;s a <code>SyntaxError</code>.</p>
<p>And in our case, the absence of <code>name</code> is an error, as users must have a <code>name</code>.</p>
<p>So let&rsquo;s throw it:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;{ &#34;age&#34;: 30 }&#39;</span>; <span style="color:#75715e">// incomplete data
</span><span style="color:#75715e"></span>
<span style="color:#66d9ef">try</span> {

  <span style="color:#66d9ef">let</span> <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#a6e22e">json</span>); <span style="color:#75715e">// &lt;-- no errors
</span><span style="color:#75715e"></span>
  <span style="color:#66d9ef">if</span> (<span style="color:#f92672">!</span><span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span>) {
<span style="color:#f92672">*!*</span>
    <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> <span style="color:#a6e22e">SyntaxError</span>(<span style="color:#e6db74">&#34;Incomplete data: no name&#34;</span>); <span style="color:#75715e">// (*)
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
  }

  <span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span> );

} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#34;JSON Error: &#34;</span> <span style="color:#f92672">+</span> <span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">message</span> ); <span style="color:#75715e">// JSON Error: Incomplete data: no name
</span><span style="color:#75715e"></span>}
</code></pre></div><p>In the line <code>(*)</code>, the <code>throw</code> operator generates a <code>SyntaxError</code> with the given <code>message</code>, the same way as JavaScript would generate it itself. The execution of <code>try</code> immediately stops and the control flow jumps into <code>catch</code>.</p>
<p>Now <code>catch</code> became a single place for all error handling: both for <code>JSON.parse</code> and other cases.</p>
<h2 id="rethrowing">Rethrowing</h2>
<p>In the example above we use <code>try...catch</code> to handle incorrect data. But is it possible that <em>another unexpected error</em> occurs within the <code>try {...}</code> block? Like a programming error (variable is not defined) or something else, not just this &ldquo;incorrect data&rdquo; thing.</p>
<p>For example:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;{ &#34;age&#34;: 30 }&#39;</span>; <span style="color:#75715e">// incomplete data
</span><span style="color:#75715e"></span>
<span style="color:#66d9ef">try</span> {
  <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#a6e22e">json</span>); <span style="color:#75715e">// &lt;-- forgot to put &#34;let&#34; before user
</span><span style="color:#75715e"></span>
  <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#34;JSON Error: &#34;</span> <span style="color:#f92672">+</span> <span style="color:#a6e22e">err</span>); <span style="color:#75715e">// JSON Error: ReferenceError: user is not defined
</span><span style="color:#75715e"></span>  <span style="color:#75715e">// (no JSON Error actually)
</span><span style="color:#75715e"></span>}
</code></pre></div><p>Of course, everything&rsquo;s possible! Programmers do make mistakes. Even in open-source utilities used by millions for decades &ndash; suddenly a bug may be discovered that leads to terrible hacks.</p>
<p>In our case, <code>try...catch</code> is placed to catch &ldquo;incorrect data&rdquo; errors. But by its nature, <code>catch</code> gets <em>all</em> errors from <code>try</code>. Here it gets an unexpected error, but still shows the same <code>&quot;JSON Error&quot;</code> message. That&rsquo;s wrong and also makes the code more difficult to debug.</p>
<p>To avoid such problems, we can employ the &ldquo;rethrowing&rdquo; technique. The rule is simple:</p>
<p><strong>Catch should only process errors that it knows and &ldquo;rethrow&rdquo; all others.</strong></p>
<p>The &ldquo;rethrowing&rdquo; technique can be explained in more detail as:</p>
<ol>
<li>Catch gets all errors.</li>
<li>In the <code>catch (err) {...}</code> block we analyze the error object <code>err</code>.</li>
<li>If we don&rsquo;t know how to handle it, we do <code>throw err</code>.</li>
</ol>
<p>Usually, we can check the error type using the <code>instanceof</code> operator:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> { <span style="color:#75715e">/*...*/</span> };
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
<span style="color:#f92672">*!*</span>
  <span style="color:#66d9ef">if</span> (<span style="color:#a6e22e">err</span> <span style="color:#66d9ef">instanceof</span> <span style="color:#a6e22e">ReferenceError</span>) {
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
    <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">&#39;ReferenceError&#39;</span>); <span style="color:#75715e">// &#34;ReferenceError&#34; for accessing an undefined variable
</span><span style="color:#75715e"></span>  }
}
</code></pre></div><p>We can also get the error class name from <code>err.name</code> property. All native errors have it. Another option is to read <code>err.constructor.name</code>.</p>
<p>In the code below, we use rethrowing so that <code>catch</code> only handles <code>SyntaxError</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;{ &#34;age&#34;: 30 }&#39;</span>; <span style="color:#75715e">// incomplete data
</span><span style="color:#75715e"></span><span style="color:#66d9ef">try</span> {

  <span style="color:#66d9ef">let</span> <span style="color:#a6e22e">user</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">JSON</span>.<span style="color:#a6e22e">parse</span>(<span style="color:#a6e22e">json</span>);

  <span style="color:#66d9ef">if</span> (<span style="color:#f92672">!</span><span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span>) {
    <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> <span style="color:#a6e22e">SyntaxError</span>(<span style="color:#e6db74">&#34;Incomplete data: no name&#34;</span>);
  }

<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">blabla</span>(); <span style="color:#75715e">// unexpected error
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

  <span style="color:#a6e22e">alert</span>( <span style="color:#a6e22e">user</span>.<span style="color:#a6e22e">name</span> );

} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {

<span style="color:#f92672">*!*</span>
  <span style="color:#66d9ef">if</span> (<span style="color:#a6e22e">err</span> <span style="color:#66d9ef">instanceof</span> <span style="color:#a6e22e">SyntaxError</span>) {
    <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#34;JSON Error: &#34;</span> <span style="color:#f92672">+</span> <span style="color:#a6e22e">err</span>.<span style="color:#a6e22e">message</span> );
  } <span style="color:#66d9ef">else</span> {
    <span style="color:#66d9ef">throw</span> <span style="color:#a6e22e">err</span>; <span style="color:#75715e">// rethrow (*)
</span><span style="color:#75715e"></span>  }
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

}
</code></pre></div><p>The error throwing on line <code>(*)</code> from inside <code>catch</code> block &ldquo;falls out&rdquo; of <code>try...catch</code> and can be either caught by an outer <code>try...catch</code> construct (if it exists), or it kills the script.</p>
<p>So the <code>catch</code> block actually handles only errors that it knows how to deal with and &ldquo;skips&rdquo; all others.</p>
<p>The example below demonstrates how such errors can be caught by one more level of <code>try...catch</code>:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">function</span> <span style="color:#a6e22e">readData</span>() {
  <span style="color:#66d9ef">let</span> <span style="color:#a6e22e">json</span> <span style="color:#f92672">=</span> <span style="color:#e6db74">&#39;{ &#34;age&#34;: 30 }&#39;</span>;

  <span style="color:#66d9ef">try</span> {
    <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span><span style="color:#f92672">*!*</span>
    <span style="color:#a6e22e">blabla</span>(); <span style="color:#75715e">// error!
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
  } <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
    <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>    <span style="color:#66d9ef">if</span> (<span style="color:#f92672">!</span>(<span style="color:#a6e22e">err</span> <span style="color:#66d9ef">instanceof</span> <span style="color:#a6e22e">SyntaxError</span>)) {
<span style="color:#f92672">*!*</span>
      <span style="color:#66d9ef">throw</span> <span style="color:#a6e22e">err</span>; <span style="color:#75715e">// rethrow (don&#39;t know how to deal with it)
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
    }
  }
}

<span style="color:#66d9ef">try</span> {
  <span style="color:#a6e22e">readData</span>();
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
<span style="color:#f92672">*!*</span>
  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#34;External catch got: &#34;</span> <span style="color:#f92672">+</span> <span style="color:#a6e22e">err</span> ); <span style="color:#75715e">// caught it!
</span><span style="color:#75715e"></span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>
}
</code></pre></div><p>Here <code>readData</code> only knows how to handle <code>SyntaxError</code>, while the outer <code>try...catch</code> knows how to handle everything.</p>
<h2 id="trycatchfinally">try&hellip;catch&hellip;finally</h2>
<p>Wait, that&rsquo;s not all.</p>
<p>The <code>try...catch</code> construct may have one more code clause: <code>finally</code>.</p>
<p>If it exists, it runs in all cases:</p>
<ul>
<li>after <code>try</code>, if there were no errors,</li>
<li>after <code>catch</code>, if there were errors.</li>
</ul>
<p>The extended syntax looks like this:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#f92672">*!*</span><span style="color:#66d9ef">try</span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!* {</span>
   ... <span style="color:#66d9ef">try</span> <span style="color:#a6e22e">to</span> <span style="color:#a6e22e">execute</span> <span style="color:#a6e22e">the</span> <span style="color:#a6e22e">code</span> ...
} <span style="color:#f92672">*!*</span><span style="color:#66d9ef">catch</span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!* (err) {</span>
   ... <span style="color:#a6e22e">handle</span> <span style="color:#a6e22e">errors</span> ...
} <span style="color:#f92672">*!*</span><span style="color:#66d9ef">finally</span><span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!* {</span>
   ... <span style="color:#a6e22e">execute</span> <span style="color:#a6e22e">always</span> ...
}
</code></pre></div><p>Try running this code:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#39;try&#39;</span> );
  <span style="color:#66d9ef">if</span> (<span style="color:#a6e22e">confirm</span>(<span style="color:#e6db74">&#39;Make an error?&#39;</span>)) <span style="color:#a6e22e">BAD_CODE</span>();
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#39;catch&#39;</span> );
} <span style="color:#66d9ef">finally</span> {
  <span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">&#39;finally&#39;</span> );
}
</code></pre></div><p>The code has two ways of execution:</p>
<ol>
<li>If you answer &ldquo;Yes&rdquo; to &ldquo;Make an error?&rdquo;, then <code>try -&gt; catch -&gt; finally</code>.</li>
<li>If you say &ldquo;No&rdquo;, then <code>try -&gt; finally</code>.</li>
</ol>
<p>The <code>finally</code> clause is often used when we start doing something and want to finalize it in any case of outcome.</p>
<p>For instance, we want to measure the time that a Fibonacci numbers function <code>fib(n)</code> takes. Naturally, we can start measuring before it runs and finish afterwards. But what if there&rsquo;s an error during the function call? In particular, the implementation of <code>fib(n)</code> in the code below returns an error for negative or non-integer numbers.</p>
<p>The <code>finally</code> clause is a great place to finish the measurements no matter what.</p>
<p>Here <code>finally</code> guarantees that the time will be measured correctly in both situations &ndash; in case of a successful execution of <code>fib</code> and in case of an error in it:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">let</span> <span style="color:#a6e22e">num</span> <span style="color:#f92672">=</span> <span style="color:#f92672">+</span><span style="color:#a6e22e">prompt</span>(<span style="color:#e6db74">&#34;Enter a positive integer number?&#34;</span>, <span style="color:#ae81ff">35</span>)

<span style="color:#66d9ef">let</span> <span style="color:#a6e22e">diff</span>, <span style="color:#a6e22e">result</span>;

<span style="color:#66d9ef">function</span> <span style="color:#a6e22e">fib</span>(<span style="color:#a6e22e">n</span>) {
  <span style="color:#66d9ef">if</span> (<span style="color:#a6e22e">n</span> <span style="color:#f92672">&lt;</span> <span style="color:#ae81ff">0</span> <span style="color:#f92672">||</span> Math.<span style="color:#a6e22e">trunc</span>(<span style="color:#a6e22e">n</span>) <span style="color:#f92672">!=</span> <span style="color:#a6e22e">n</span>) {
    <span style="color:#66d9ef">throw</span> <span style="color:#66d9ef">new</span> Error(<span style="color:#e6db74">&#34;Must not be negative, and also an integer.&#34;</span>);
  }
  <span style="color:#66d9ef">return</span> <span style="color:#a6e22e">n</span> <span style="color:#f92672">&lt;=</span> <span style="color:#ae81ff">1</span> <span style="color:#f92672">?</span> <span style="color:#a6e22e">n</span> <span style="color:#f92672">:</span> <span style="color:#a6e22e">fib</span>(<span style="color:#a6e22e">n</span> <span style="color:#f92672">-</span> <span style="color:#ae81ff">1</span>) <span style="color:#f92672">+</span> <span style="color:#a6e22e">fib</span>(<span style="color:#a6e22e">n</span> <span style="color:#f92672">-</span> <span style="color:#ae81ff">2</span>);
}

<span style="color:#66d9ef">let</span> <span style="color:#a6e22e">start</span> <span style="color:#f92672">=</span> Date.<span style="color:#a6e22e">now</span>();

<span style="color:#66d9ef">try</span> {
  <span style="color:#a6e22e">result</span> <span style="color:#f92672">=</span> <span style="color:#a6e22e">fib</span>(<span style="color:#a6e22e">num</span>);
} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#a6e22e">result</span> <span style="color:#f92672">=</span> <span style="color:#ae81ff">0</span>;
<span style="color:#f92672">*!*</span>
} <span style="color:#66d9ef">finally</span> {
  <span style="color:#a6e22e">diff</span> <span style="color:#f92672">=</span> Date.<span style="color:#a6e22e">now</span>() <span style="color:#f92672">-</span> <span style="color:#a6e22e">start</span>;
}
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

<span style="color:#a6e22e">alert</span>(<span style="color:#a6e22e">result</span> <span style="color:#f92672">||</span> <span style="color:#e6db74">&#34;error occurred&#34;</span>);

<span style="color:#a6e22e">alert</span>( <span style="color:#e6db74">`execution took </span><span style="color:#e6db74">${</span><span style="color:#a6e22e">diff</span><span style="color:#e6db74">}</span><span style="color:#e6db74">ms`</span> );
</code></pre></div><p>You can check by running the code with entering <code>35</code> into <code>prompt</code> &ndash; it executes normally, <code>finally</code> after <code>try</code>. And then enter <code>-1</code> &ndash; there will be an immediate error, and the execution will take <code>0ms</code>. Both measurements are done correctly.</p>
<p>In other words, the function may finish with <code>return</code> or <code>throw</code>, that doesn&rsquo;t matter. The <code>finally</code> clause executes in both cases.</p>
<p>```smart header=&ldquo;Variables are local inside <code>try...catch...finally</code>&rdquo;
Please note that <code>result</code> and <code>diff</code> variables in the code above are declared <em>before</em> <code>try...catch</code>.</p>
<p>Otherwise, if we declared <code>let</code> in <code>try</code> block, it would only be visible inside of it.</p>
<pre><code>
````smart header=&quot;`finally` and `return`&quot;
The `finally` clause works for *any* exit from `try...catch`. That includes an explicit `return`.

In the example below, there's a `return` in `try`. In this case, `finally` is executed just before the control returns to the outer code.

```js run
function func() {

  try {
*!*
    return 1;
*/!*

  } catch (err) {
    /* ... */
  } finally {
*!*
    alert( 'finally' );
*/!*
  }
}

alert( func() ); // first works alert from finally, and then this one
</code></pre><pre><code>
````smart header=&quot;`try...finally`&quot;

The `try...finally` construct, without `catch` clause, is also useful. We apply it when we don't want to handle errors here (let them fall through), but want to be sure that processes that we started are finalized.

```js
function func() {
  // start doing something that needs completion (like measurements)
  try {
    // ...
  } finally {
    // complete that thing even if all dies
  }
}
```
In the code above, an error inside `try` always falls out, because there's no `catch`. But `finally` works before the execution flow leaves the function.
</code></pre><h2 id="global-catch">Global catch</h2>
<pre><code class="language-warn" data-lang="warn">The information from this section is not a part of the core JavaScript.
</code></pre><p>Let&rsquo;s imagine we&rsquo;ve got a fatal error outside of <code>try...catch</code>, and the script died. Like a programming error or some other terrible thing.</p>
<p>Is there a way to react on such occurrences? We may want to log the error, show something to the user (normally they don&rsquo;t see error messages), etc.</p>
<p>There is none in the specification, but environments usually provide it, because it&rsquo;s really useful. For instance, Node.js has <a href="https://nodejs.org/api/process.html#process_event_uncaughtexception"><code>process.on(&quot;uncaughtException&quot;)</code></a> for that. And in the browser we can assign a function to the special <a href="mdn:api/GlobalEventHandlers/onerror">window.onerror</a> property, that will run in case of an uncaught error.</p>
<p>The syntax:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js">window.<span style="color:#a6e22e">onerror</span> <span style="color:#f92672">=</span> <span style="color:#66d9ef">function</span>(<span style="color:#a6e22e">message</span>, <span style="color:#a6e22e">url</span>, <span style="color:#a6e22e">line</span>, <span style="color:#a6e22e">col</span>, <span style="color:#a6e22e">error</span>) {
  <span style="color:#75715e">// ...
</span><span style="color:#75715e"></span>};
</code></pre></div><dl>
<dt><code>message</code></dt>
<dd>Error message.</dd>
<dt><code>url</code></dt>
<dd>URL of the script where error happened.</dd>
<dt><code>line</code>, <code>col</code></dt>
<dd>Line and column numbers where error happened.</dd>
<dt><code>error</code></dt>
<dd>Error object.</dd>
</dl>
<p>For instance:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-html" data-lang="html">&lt;<span style="color:#f92672">script</span>&gt;
<span style="color:#f92672">*!*</span>
  window.<span style="color:#a6e22e">onerror</span> <span style="color:#f92672">=</span> <span style="color:#66d9ef">function</span>(<span style="color:#a6e22e">message</span>, <span style="color:#a6e22e">url</span>, <span style="color:#a6e22e">line</span>, <span style="color:#a6e22e">col</span>, <span style="color:#a6e22e">error</span>) {
    <span style="color:#a6e22e">alert</span>(<span style="color:#e6db74">`</span><span style="color:#e6db74">${</span><span style="color:#a6e22e">message</span><span style="color:#e6db74">}</span><span style="color:#e6db74">\n At </span><span style="color:#e6db74">${</span><span style="color:#a6e22e">line</span><span style="color:#e6db74">}</span><span style="color:#e6db74">:</span><span style="color:#e6db74">${</span><span style="color:#a6e22e">col</span><span style="color:#e6db74">}</span><span style="color:#e6db74"> of </span><span style="color:#e6db74">${</span><span style="color:#a6e22e">url</span><span style="color:#e6db74">}</span><span style="color:#e6db74">`</span>);
  };
<span style="color:#f92672">*</span><span style="color:#960050;background-color:#1e0010">/!*</span>

  <span style="color:#66d9ef">function</span> <span style="color:#a6e22e">readData</span>() {
    <span style="color:#a6e22e">badFunc</span>(); <span style="color:#75715e">// Whoops, something went wrong!
</span><span style="color:#75715e"></span>  }

  <span style="color:#a6e22e">readData</span>();
&lt;/<span style="color:#f92672">script</span>&gt;
</code></pre></div><p>The role of the global handler <code>window.onerror</code> is usually not to recover the script execution &ndash; that&rsquo;s probably impossible in case of programming errors, but to send the error message to developers.</p>
<p>There are also web-services that provide error-logging for such cases, like <a href="https://errorception.com">https://errorception.com</a> or <a href="http://www.muscula.com">http://www.muscula.com</a>.</p>
<p>They work like this:</p>
<ol>
<li>We register at the service and get a piece of JS (or a script URL) from them to insert on pages.</li>
<li>That JS script sets a custom <code>window.onerror</code> function.</li>
<li>When an error occurs, it sends a network request about it to the service.</li>
<li>We can log in to the service web interface and see errors.</li>
</ol>
<h2 id="summary">Summary</h2>
<p>The <code>try...catch</code> construct allows to handle runtime errors. It literally allows to &ldquo;try&rdquo; running the code and &ldquo;catch&rdquo; errors that may occur in it.</p>
<p>The syntax is:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-js" data-lang="js"><span style="color:#66d9ef">try</span> {
  <span style="color:#75715e">// run this code
</span><span style="color:#75715e"></span>} <span style="color:#66d9ef">catch</span> (<span style="color:#a6e22e">err</span>) {
  <span style="color:#75715e">// if an error happened, then jump here
</span><span style="color:#75715e"></span>  <span style="color:#75715e">// err is the error object
</span><span style="color:#75715e"></span>} <span style="color:#66d9ef">finally</span> {
  <span style="color:#75715e">// do in any case after try/catch
</span><span style="color:#75715e"></span>}
</code></pre></div><p>There may be no <code>catch</code> section or no <code>finally</code>, so shorter constructs <code>try...catch</code> and <code>try...finally</code> are also valid.</p>
<p>Error objects have following properties:</p>
<ul>
<li><code>message</code> &ndash; the human-readable error message.</li>
<li><code>name</code> &ndash; the string with error name (error constructor name).</li>
<li><code>stack</code> (non-standard, but well-supported) &ndash; the stack at the moment of error creation.</li>
</ul>
<p>If an error object is not needed, we can omit it by using <code>catch {</code> instead of <code>catch (err) {</code>.</p>
<p>We can also generate our own errors using the <code>throw</code> operator. Technically, the argument of <code>throw</code> can be anything, but usually it&rsquo;s an error object inheriting from the built-in <code>Error</code> class. More on extending errors in the next chapter.</p>
<p><em>Rethrowing</em> is a very important pattern of error handling: a <code>catch</code> block usually expects and knows how to handle the particular error type, so it should rethrow errors it doesn&rsquo;t know.</p>
<p>Even if we don&rsquo;t have <code>try...catch</code>, most environments allow us to setup a &ldquo;global&rdquo; error handler to catch errors that &ldquo;fall out&rdquo;. In-browser, that&rsquo;s <code>window.onerror</code>.</p>
</main>


<div class="modal fade" id="noteModel" tabindex="-1" aria-labelledby="noteModelLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="noteModelLabel">Note</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <textarea class="form-control" id="noteText" rows="3"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


    </div>
    
  </main>
  
  



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confimation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
          <button type="button" class="btn btn-primary">Yes</button>
        </div>
      </div>
    </div>
  </div>

<div aria-live="polite" aria-atomic="true">
  <div class="toast-container position-absolute top-0 start-0 p-5 mt-5" id="toast-container">
    
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
<script type="text/javascript" src="/js/app.js"></script>



  
  
  

<script type="text/javascript" src="/js/chapter.js"></script>


  
</body>

</html>